"""Machine-readable reason codes.

Every constant below except the ones under SKELETON-ONLY already appears,
verbatim, in a ratified document (docs/21_GOVERNANCE_CORE_SPEC.md,
docs/23_CAPABILITY_MODEL.md, docs/24_APPROVAL_MODEL.md,
governance/schemas/policy-decision.schema.json). This module does not
introduce new governance semantics; it gives the ratified vocabulary a
single importable source so no two call sites can accidentally spell a
code two different ways.

Shape must always satisfy policy-decision.schema.json's reasonCode
pattern: ^[A-Z][A-Z0-9_]{2,63}$
"""

from __future__ import annotations

# --- Kernel / authority --------------------------------------------------
INVARIANT_MATCH = "INVARIANT_MATCH"
CLASS_D_PROHIBITED = "CLASS_D_PROHIBITED"
PROTECTED_AUTHORITY_PATH = "PROTECTED_AUTHORITY_PATH"  # docs/21 cases #16/#17
AUDIT_IMMUTABLE = "AUDIT_IMMUTABLE"  # docs/21 case #18
KERNEL_UNAVAILABLE = "KERNEL_UNAVAILABLE"
KERNEL_CHECKSUM_MISMATCH = "KERNEL_CHECKSUM_MISMATCH"

# --- Policy engine ---------------------------------------------------------
APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
GOVERNANCE_UNAVAILABLE = "GOVERNANCE_UNAVAILABLE"
KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
POLICY_VERSION_MISMATCH = "POLICY_VERSION_MISMATCH"
POLICY_BUNDLE_UNAVAILABLE = "POLICY_BUNDLE_UNAVAILABLE"
POLICY_BUNDLE_INVALID = "POLICY_BUNDLE_INVALID"
UNCLASSIFIED_RESOURCE = "UNCLASSIFIED_RESOURCE"
POLICY_NO_MATCHING_RULE = "POLICY_NO_MATCHING_RULE"
SCHEMA_INVALID = "SCHEMA_INVALID"
DUPLICATE_REQUEST = "DUPLICATE_REQUEST"
AUDIT_UNAVAILABLE = "AUDIT_UNAVAILABLE"
GOVERNANCE_MEDIATION_UNAVAILABLE = "GOVERNANCE_MEDIATION_UNAVAILABLE"  # docs/21 case #14b

# --- Approval ---------------------------------------------------------------
SELF_APPROVAL_FORBIDDEN = "SELF_APPROVAL_FORBIDDEN"
APPROVAL_EXPIRED = "APPROVAL_EXPIRED"

# --- Secrets -----------------------------------------------------------------
SECRET_VALUE_DISCLOSURE_FORBIDDEN = "SECRET_VALUE_DISCLOSURE_FORBIDDEN"
SECRET_REFERENCE_APPROVAL_REQUIRED = "SECRET_REFERENCE_APPROVAL_REQUIRED"

# --- Capability --------------------------------------------------------------
CAPABILITY_MALFORMED = "CAPABILITY_MALFORMED"
CAPABILITY_HEADER_INVALID = "CAPABILITY_HEADER_INVALID"
CAPABILITY_ALGORITHM_DENIED = "CAPABILITY_ALGORITHM_DENIED"
CAPABILITY_TYPE_DENIED = "CAPABILITY_TYPE_DENIED"
CAPABILITY_KEY_UNKNOWN = "CAPABILITY_KEY_UNKNOWN"
CAPABILITY_SIGNATURE_INVALID = "CAPABILITY_SIGNATURE_INVALID"
CAPABILITY_CLAIMS_INVALID = "CAPABILITY_CLAIMS_INVALID"
CAPABILITY_AUDIENCE_MISMATCH = "CAPABILITY_AUDIENCE_MISMATCH"
CAPABILITY_NOT_YET_VALID = "CAPABILITY_NOT_YET_VALID"
CAPABILITY_EXPIRED = "CAPABILITY_EXPIRED"
CAPABILITY_REVOKED = "CAPABILITY_REVOKED"
CAPABILITY_REPLAY_DENIED = "CAPABILITY_REPLAY_DENIED"
CAPABILITY_POLICY_MISMATCH = "CAPABILITY_POLICY_MISMATCH"
CAPABILITY_RESOURCE_MISMATCH = "CAPABILITY_RESOURCE_MISMATCH"

# --- SKELETON-ONLY ------------------------------------------------------------
# Not part of the ratified reason-code vocabulary. Used exclusively to
# distinguish "cryptography is intentionally not implemented in this
# skeleton" from "a signature was actually presented and failed to verify"
# (CAPABILITY_SIGNATURE_INVALID). See docs/30_GOVERNANCE_IMPLEMENTATION_SKELETON.md.
CAPABILITY_CRYPTO_NOT_IMPLEMENTED = "CAPABILITY_CRYPTO_NOT_IMPLEMENTED"
AUDIT_CANONICALIZER_NOT_IMPLEMENTED = "AUDIT_CANONICALIZER_NOT_IMPLEMENTED"
